name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Copy .env
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/parkly-backend
          git pull
          php composer.phar install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan db:seed --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php-fpm
          sudo systemctl restart httpd 