name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Copy .env for testing
      run: |
        cp .env.example .env
        echo "APP_ENV=testing" >> .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=:memory:" >> .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run PHPUnit Tests
      run: |
        php artisan config:clear
        php artisan test --env=testing

    # If tests fail, the workflow will stop here
    - name: Prepare for Production Deployment
      if: success()
      run: |
        rm -rf vendor
        cp .env.example .env
        composer install --no-dev --optimize-autoloader

    - name: Deploy to Server
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.INSTANCE_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/parkly-backend
          git pull
          php composer.phar install --no-dev --optimize-autoloader
          php artisan migrate
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo chown -R apache:apache storage
          sudo chmod -R 777 storage
          php artisan vendor:publish --provider "L5Swagger\L5SwaggerServiceProvider" --force
          php artisan l5-swagger:generate
          sudo systemctl restart php-fpm
          sudo systemctl restart httpd 